### DISCUSSION TITLE
Edge lines over edge labels

### DISCUSSION THREAD

**Discussion by ShahriarKh** [xyflow/xyflow#2250] [Q&A]
![image](https://user-images.githubusercontent.com/31452340/176275454-de367348-b11e-47c9-8b77-b2c7879d5d27.png)
How can I prevent this? I tried changing z-index of both the label and line, and also tried passing `zIndex: 0` to edges, but no luck.

This is my custom edge:
```jsx
import css from "./CustomEdge.module.scss";
import { getBezierPath, getBezierEdgeCenter } from "react-flow-renderer";
import { useFormContext } from "react-hook-form";

const foreignObjectSize = 40;

export default function CustomEdge({
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    style = {},
    markerEnd,
}) {
    const { register } = useFormContext();

    const edgePath = getBezierPath({
        sourceX,
        sourceY,
        sourcePosition,
        targetX,
        targetY,
        targetPosition,
    });

    const [centerX, centerY, offsetX, offsetY] = getBezierEdgeCenter({
        sourceX,
        sourceY,
        targetX,
        targetY,
        curvature: 0.25,
    });


    return (
        <>
            <path
                id={id}
                style={style}
                className="react-flow__edge-path"
                d={edgePath}
                markerEnd={markerEnd}
                // ref={ref}
            />
            <foreignObject
                width={foreignObjectSize}
                height={foreignObjectSize}
                x={centerX - foreignObjectSize / 2}
                y={centerY - foreignObjectSize / 3.5}
                className="edgebutton-foreignobject"
                requiredExtensions="http://www.w3.org/1999/xhtml"
            >
                <input className={css.cost} {...register(id)} />
            </foreignObject>
        </>
    );
}
```

```scss
@use "colors" as *;

.cost {
    background-color: $grey;
    border: none;
    color: white;
    border-radius: 6px;
    padding: 2px;
    text-align: center;
    width: 100%;
    box-shadow: 0 2px 6px 1px rgba(0,0,0,0.3);
    border: solid 2px transparent;
    transition: all 0.2s;
    
    &:focus {
        border: solid 2px $teal;
        outline: none;
    }
}
```
