### DISCUSSION TITLE
Is it possible to custom animation of edge?

### DISCUSSION THREAD

**Discussion by devpola** [xyflow/xyflow#2332] [Q&A] [answered]
Is it possible to custom animation of edge? 
For example, blink animation, animation like extending in both directions from the middle of edge, and so on.

**Comment by moklick** [comment, marked as answer]
Yes, everything what you can do with SVG paths is possible. The current animation looks like this:

```css
.react-flow__edge.animated path {
  stroke-dasharray: 5;
  animation: dashdraw 0.5s linear infinite;
}

@keyframes dashdraw {
  from {
    stroke-dashoffset: 10;
  }
}
```

a blink animation could be implemented in this way:

```css
.react-flow__edge.animated path {
  stroke-opacity: 0.5;
  animation: blink 0.5s linear infinite;
}

@keyframes blink {
  from {
    stroke-opacity: 1;
  }
}
```
