### DISCUSSION TITLE
Changing the cursor when hovering the react-flow pane.

### DISCUSSION THREAD

**Discussion by TDay1** [xyflow/xyflow#3216] [Q&A]
Hi!
For my use case of this library I need to change the cursor that appears when hovering the react-flow pane from the default (grabber) to the pointer cursor. I was unable to find anything on this in the docs/random googling.
Any ideas?

**Comment by moklick** [comment]
you can use regular CSS to achieve this:

```css
.react-flow__pane {
  cursor: default;
}
```

**Reply by moklick** [reply]
answered here: #4075

**Reply by DhruvKulkarni86** [reply]
If we're using tailwind, where would I apply the 'cursor-none' class? Tried it on the main ReactFlow component but doesn't work

**Reply by pchunky** [reply]
You can't use Tailwind CSS utilities to override this. You need to apply the CSS style.

Also, try this instead. I inspected the component and saw that the `cursor: pointer;` style came from `.selection`. 
```css
.react-flow__pane.selection {
  cursor: default;
}
```

If you still want to select the `.react-flow__pane` parent, then apply `!important`.
```css
.react-flow__pane {
  cursor: default !important;
}
```
