### DISCUSSION TITLE
How to disable focus and click on a edge?

### DISCUSSION THREAD

**Discussion by Jasminou** [xyflow/xyflow#3241] [Q&A] [answered]
Hi, I would like to know how to disable the focus/click on the edge when onEdgeClick is set to undefined. Currently, the default behavior allows clicking and focusing on the clicked edge, which inverts the color.

I want to enable clicking on the edge only when onEdgeClick is not undefined, so the pointer cursor won't mislead the users.

**Comment by moklick** [comment]
Are you working with custom edges or the default ones?

**Comment by Jasminou** [comment]
Hi I'm working with a custom edges 
already tried   elementsSelectable={false} but since it's custom one doesn't seems to work

**Reply by bcakmakoglu** [reply]
`elementsSelectable={true}` would mean it *is clickable* though 🤔

**Reply by Jasminou** [reply]
no sorry it was a copy past error i mean i tried to turn if off by setting to false still doesn't work

**Reply by bcakmakoglu** [reply, marked as answer]
Well, the easiest way should be to just use css to disable pointer events on your custom edge to disable clicking.

```css
/* `custom` is a pseudo edge-type I chose, the actual css class is whatever your edge type is named, e.g. `type: 'my-edge` -> `.react-flow__edge-my-edge` */
.react-flow__edge-custom {
	/* If necessary, add !important to the rule */
	pointer-events: none;
}
```

Disabling focus can be done by using `edge.focusable` or if you want to disable it for *all* edges you can use the `edgesFocusable` prop.

```tsx
<ReactFlow edgesFocusable={false} ...>...</ReactFlow>
```
