### DISCUSSION TITLE
Add node button always at the end of the flow

### DISCUSSION THREAD

**Discussion by Adam-Collier** [xyflow/xyflow#3500] [Q&A]
Hi guys, starting playing around with react flow this week and I'm wanting to add something like the below:

<img width="609" alt="image" src="https://github.com/wbkd/react-flow/assets/20065745/adef38f9-b2cc-433e-89a6-1e4427acf040">

Where there is always an add button at the end so you can easily add another node to the end :) If you have some code you could share that would be great! But if not, if you could share the approach I should take that would be wonderful

**Comment by bcakmakoglu** [comment]
Well, this is basically a [pro example](https://reactflow.dev/docs/examples/layout/workflow-builder-starter/), which you can access for a subscription.

**Reply by Adam-Collier** [reply]
Ahh man I didn't realise it was in an example only available in the pro subscription 😅  I don't mind implementing it myself, I just need an idea of how I could potentially go about creating it

**Reply by moklick** [reply]
It's a custom node in the form of a button.

**Comment by edman-cota** [comment]
I have done something similar and had to use a relative div as a workaround:
![image](https://github.com/wbkd/react-flow/assets/54090748/839bbf91-ca8d-46bd-b5f6-e9b59a4fb828)

I have to create a custom node like this:
```javascript
import Connector from './Connector';


const CustomNode = ({ id, data }) => {
  return (
    <>
      <div className='custom-node__header'>
        <div className='custom-node__header-label'>{data.label}</div>
        <div className='custom-node__header-title'>{data.header.title}</div>
      </div>
      <div className='custom-node__body'>
        <Connector />
      </div>
    </>
  );
};

export default CustomNode;

```
Then my Connector component:
```javascript
import styles from './Connector.module.scss';
import { MdOutlineAdd } from 'react-icons/md';

const Connector = () => {
  const handleConnectoClicked = () => {
    console.log('Clicked');
  };

  return (
    <div className={styles.connector}>
      <div className={styles.lineConnector}></div>
      <div className={styles.nodeConnector} onClick={handleConnectoClicked}>
        <MdOutlineAdd />
      </div>
    </div>
  );
};

export default Connector;
```

And it's css like this:
```css
.connector {
  position: absolute;
  right: -50px;
  width: 50px;
  align-items: center;
  display: flex;
  justify-content: center;

  .lineConnector {
    flex: 1;

    white-space: nowrap;
    position: relative;
    overflow: hidden;

    &::after {
      content: '-----';
      letter-spacing: 1px;
      font-size: 10px;
      color: #9cbfdb;
      display: inline-block;
      vertical-align: 2px;
    }
  }

  .nodeConnector {
    height: 26px;
    width: 26px;
    border-radius: 50%;
    background-color: #03989e;
    cursor: pointer;
    display: flex;
    fill: white;
    color: white;
    justify-content: center;
    align-items: center;
  }
}

I hope this would help you.

```
