### DISCUSSION TITLE
Highligth border on selected nodes for custom nodes

### DISCUSSION THREAD

**Discussion by crmoratelli** [xyflow/xyflow#4648] [Q&A] [answered]
Hello,

I have noticed that the examples involving custom nodes do not include the feature to highlight borders when selected. You can see an example here:

https://reactflow.dev/examples/nodes/custom-node

I would like to add a border highlighting effect for selected nodes, but I haven't been able to find a way to do so.

Any help?? Thanks!

**Comment by bcakmakoglu** [comment]
Some basic css would already do the trick, for example
```css
.react-flow__node-selectorNode.selected {
  border: 1px solid pink !important;
}
```

[Here's an example sandbox.](https://codesandbox.io/p/sandbox/solitary-pine-5p56pf?file=%2Findex.css%3A9%2C1)
