### DISCUSSION TITLE
Set start position of edge as anywhere

### DISCUSSION THREAD

**Discussion by yasmro** [xyflow/xyflow#4967] [Q&A]
We would like to set the start position as the right side wherever the user connects any position in Handle area.

![image](https://github.com/user-attachments/assets/441e824a-9bc5-4f3d-9947-352eae5c1d58)

Prerequisite: Set the green whole area as Handle Component (User can start connecting from anywhere in the green area).

When the user click the area and drag to anywhere, the start position will be centering of the green area. We would like to set the start position as right side of the green area.

We would like to set the start position as the right side wherever the user connects any position on the green area. Is it possible to do this?

Here is the code snippet:

`CustomNode.ts`
```typescript
<Box>
  <div style={{ width: '100%', position: 'relative' }}>
    <Box w="100%" ps="0.5rem" pe="0.75rem" py="0.25rem" bg="teal.500" rounded="4px">
      <Flex alignItems="center">
        <Icon as={WebhookOutlined} color="white" fontSize="lg" mr="0.25rem" />
        <TextWithLineBreaks text={t('scenario:node.channel.trigger')} color="white" fontWeight={600} fontSize="75%" />
      </Flex>
    </Box>
    <Handle type="source" className="customHandle" position={Position.Right} />
  </div>
</Box>
```

RemovableEdge.tsx

```typescript
import { Box, IconButton } from '@chakra-ui/react';
import { CloseOutlined } from '@mui/icons-material';
import { BaseEdge, EdgeLabelRenderer, EdgeProps, getSmoothStepPath, useReactFlow } from '@xyflow/react';
import React, { useContext } from 'react';
import { scenarioCanvasMode } from '@/constants/scenarioCanvasMode';
import { ScenarioFlowContext } from '@/providers/ScenarioFlowContext';

function RemovableEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style = {},
  markerEnd,
}: EdgeProps) {
  const { setEdges } = useReactFlow();
  const { mode } = useContext(ScenarioFlowContext);
  const isInteractive = mode === scenarioCanvasMode.edit;
  const [edgePath, labelX, labelY] = getSmoothStepPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  const onEdgeLabelClick = () => {
    setEdges((edges) => edges.filter((edge) => edge.id !== id));
  };

  return (
    <>
      <BaseEdge path={edgePath} markerEnd={markerEnd} style={style} />
      <EdgeLabelRenderer>
        {isInteractive && (
          <Box
            sx={{
              position: 'absolute',
              transform: `translate(-50%, -50%) translate(${labelX}px,${labelY}px)`,
              fontSize: 8,
              // everything inside EdgeLabelRenderer has no pointer events by default
              // if you have an interactive element, set pointer-events: all
              pointerEvents: 'all',
              zIndex: 1000,
            }}
          >
            <IconButton
              onClick={onEdgeLabelClick}
              isRound
              variant="solid"
              style={{ backgroundColor: 'var(--color-edge)', color: 'white' }}
              aria-label="Remove Edge"
              opacity={0}
              _hover={{ opacity: 1 }}
              icon={<CloseOutlined fill="white" />}
            />
          </Box>
        )}
      </EdgeLabelRenderer>
    </>
  );
}

export default RemovableEdge;
```

`style.css` which describes `customHandle` class
```css
.customHandle {
  width: 100% !important;
  height: 100% !important;
  position: absolute !important;
  background: transparent !important;
  top: 0 !important;
  left: 0 !important;
  border-radius: 0 !important;
  transform: none !important;
  border: none !important;
}

.react-flow__handle-left.customHandle::after {
  content: '';
  background: none !important;
}

.react-flow__handle-right.customHandle::before {
  content: '';
  position: absolute;
  top: 50% !important;
  right: -24px !important;
  transform: translate(0, -50%);
  min-width: 5px;
  min-height: 5px;
  width: 24px !important;
  height: 18px !important;
  background: var(--color-edge) !important;
  background: radial-gradient(circle, white 30%, pink 31%);
  border: 1px solid var(--color-edge) !important;
  border-radius: 2px !important;
}

.react-flow__handle-right.customHandle::after {
  content: '';
  position: absolute;
  top: 50% !important;
  left: calc(100% + 5px) !important;
  transform: translate(0, -50%) !important;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  z-index: var(--z-index-handle) !important;
}
```
