### DISCUSSION TITLE
Feature: possibility to define custom edge anchor shape

### DISCUSSION THREAD

**Discussion by ambroseus** [xyflow/xyflow#959] [Ideas]
As for now there is a dedicated component `EdgeAnchor` with circle svg shape by default
it will be helpful to have an ability to define custom shape by overwritten this component

**Comment by moklick** [comment]
Do you really need a custom shape or would it be sufficient to be able to pass the radius of the `EdgeAnchor` as a prop?

**Reply by ambroseus** [reply]
mm.. I thought about for.ex semi-circles oriented according to handle position, but what would be really useful is:
 - yes, ability to specify different anchor's circle radius
 - ability to customize shape styles (for.ex highlight on mouse hover)

**Reply by ambroseus** [reply]
aha.. shape style already customizable :)
```css
circle.react-flow__edgeupdater:hover {
  stroke: #aaa;
  stroke-width: 1;
  stroke-dasharray: 2;
}
```
![Selection_005](https://user-images.githubusercontent.com/380645/109788675-34b0e680-7c18-11eb-85ee-99cf8169e55c.jpg)
