### DISCUSSION TITLE
Custom edge selected color

### DISCUSSION THREAD

**Discussion by mttjcksn** [xyflow/xyflow#993] [Q&A] [answered]
Hey,

Thanks for the awesome library. How can I change the colour of a custom edge when it is selected?

Many thanks

**Comment by moklick** [comment, marked as answer]
We append the class name `selected` to a selected edge that you can use to style the selected edge.

**Reply by mttjcksn** [reply]
Thanks, I can see that the selected className is appended to the g tag that contains the custom edge.  I am using a custom edge in the same way as [this example](https://reactflow.dev/examples/edges/) , and trying to style the path when selected, but simply adding a .selected css style is not working.  Do you have any examples?

**Reply by moklick** [reply]
When you want to apply to all selected paths, do:

```css 
.react-flow__edge.selected .react-flow__edge-path {
  stroke-width: 15px;
}
```

If you only want to apply it for your custom edge:

```css
.react-flow__edge-custom.selected .react-flow__edge-path {
  stroke-width: 10px;
}
```

When you have a lot of custom styles you can also use the unstyled version of React Flow https://reactflow.dev/docs/theming/
