### ISSUE TITLE
SvelteFlow: Adjusting styles of `Controls`

### ISSUE THREAD

**Issue by kerem0comert** [xyflow/xyflow#4394]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version:  ^0.1.3
- Browser and version:  Brave 1.67.119 Chromium: 126.0.6478.114 ( 
- OS and version: Windows 11

### Describe the Bug

Hello,

I have the following code snippet:

```svelte
<div style="height:86vh; position:relative;" bind:clientHeight bind:clientWidth>
  <Palette />
  <SvelteFlow
    initialViewport={INITIAL_VIEWPORT}
    nodes={nodesWritable}
    edges={edgesWritable}
    nodeTypes={STATE_TYPE_TO_SVELTE_NODE_COMPONENT}
    edgeTypes={EDGE_TYPE_TO_SVELTE_EDGE_COMPONENT}
    on:nodecontextmenu={handleContextMenu}
    on:paneclick={handlePaneClick}
    on:dragover={onDragOver}
    on:drop={onDrop}
    on:nodeclick={handleNodeClick}
    onconnectstart={handleEdgeConnectStart}
  >
    <div class="controls">
    <Controls orientation="horizontal">
      <ControlButton on:click={() => console.log('⚡️')}>⚡️</ControlButton>
    </Controls>
  </div>
    <Background variant={BackgroundVariant.Lines} />
    <MiniMap />
  </SvelteFlow>
  {#if contextMenuProps}
    <ContextMenu
      onClick={handlePaneClick}
      on:nodeDeleted={(e) => handleNodeDeleted(e.detail.id)}
      on:nodeDuplicated={handleNodeDuplicated}
      id={contextMenuProps.id}
      top={contextMenuProps.top}
      left={contextMenuProps.left}
      right={contextMenuProps.right}
      bottom={contextMenuProps.bottom}
    />
  {/if}
</div>

<style global>
  .controls {
    @apply absolute bottom-8 p-4;
    left: 20%;
    font-size: 4rem;
  }
  .svelte-flow__controls .svelte-flow__controls-button {
    width: 50px;  
    height: 50px; 
  }

  .svelte-flow__controls .svelte-flow__controls-button svg {
    width: 40px; 
    height: 40px; 
  }
</style>
```

And I am trying to adjust the styles of the `Controls` component, specifically to make it bigger. As you see I have a custom `ControlButton` and when I add `font-size: 4rem;` to the `.controls` class style, it indeed gets bigger, but the other default icons remain. I tried to target them using the two styles you see above but it did not work. Is there a recommended way to style the `Controls` in general? Thanks.

### Steps to reproduce the bug or issue

1. See the `Controls` component

### Expected behavior

I expect to be able to style the `Controls` component.

**Comment by moklick** [comment]
For the SVGs you need to overwrite `max-width` and `max-height`. Does that work?

**Comment by moklick** [comment]
`100` is not a valid value for `max-width` / `max-height`. Try:

```css
<style>
  .controls {
    @apply absolute bottom-8 p-4;
    left: 20%;
    font-size: 100px;
  }

  :global(.svelte-flow__controls .svelte-flow__controls-button) {
   width: 100px;  
   height: 100px; 
  }

  :global(.svelte-flow__controls .svelte-flow__controls-button svg) {
    max-width: 100px; 
    max-height: 100px; 
  }
</style>
```
