### ISSUE TITLE
isVisible support for Handle

### ISSUE THREAD

**Issue by andreasvirkus** [xyflow/xyflow#4650]
### Please describe the feature that you want to propose

Hi team!

I'd love for `<Handle />` to also support the `isVisible` prop, like `<NodeResizer />` does. Ideally, there'd also be some way to only show the connection handles of other nodes once the edge is actually dragged over that node, not before (FigJam and Miro both behave like this)

**Comment by peterkogo** [comment]
You can implement this with css only actually. [Here is a codesandbox](https://codesandbox.io/p/sandbox/j2qtsx) illustrating it.
```css
/* Hide handles when not in focus */
.flow .react-flow__node-customnode .react-flow__handle {
  opacity: 0;
}

/* Show handles if inside connectionRadius while making a connection */
.flow .react-flow__node-customnode .react-flow__handle.connectingto {
  opacity: 1;
}
```

I will close this for now. Don't hesitate to continue the discussion or reopen the issue if any problems persist.
