### ISSUE TITLE
Connection Line SVG not visible outside of react-flow__viewport

### ISSUE THREAD

**Issue by hamishcraze** [xyflow/xyflow#4776]
### What platform were you using when you found the bug?

"devDependencies": {
    "@mendix/pluggable-widgets-tools": "^10.15.0",
    "@types/big.js": "^6.0.2"
  },
  "dependencies": {
    "@types/web": "^0.0.175",
    "@xyflow/react": "^12.2.1",
    "classnames": "^2.2.6"
  }

### Describe the Bug

When drawing a connection line between two edges, the SVG of the connection line does not render if the node is placed outside of the viewport.

In the below picture I am creating a connection between the State 1 and State 2 initiated via the bottom handle of state 1. 
As you can see, the SVG of the connection line is only partially visible. 
![image](https://github.com/user-attachments/assets/685a0d92-643b-4c53-b05f-448ad4cdca25)

When examining the html, we see that the Connection line SVG only becomes visible when it overlaps with the boundaries of  the "react-flow__viewport" div. 
![image](https://github.com/user-attachments/assets/9c2442b2-7361-476f-b5fa-63adcb525c7f)

I am not able to find a reason for this. Please assist if possible. 

### Steps to reproduce the bug or issue

Described above. 

### Expected behavior

I expect the Connection line svg to be visible.

**Comment by bcakmakoglu** [comment]
Are you sure that these styles are applied?

![image](https://github.com/user-attachments/assets/30ebc8f0-4320-4978-afae-6870bb2a9c69)

Might be that something in your setup overwrites `overflow: visible`.

**Comment by hamishcraze** [comment]
I just implemented th

> Are you sure that these styles are applied?
> 
> ![image](https://private-user-images.githubusercontent.com/78412429/382264948-30ebc8f0-4320-4978-afae-6870bb2a9c69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjAwMzUsIm5iZiI6MTczMDQ1OTczNSwicGF0aCI6Ii83ODQxMjQyOS8zODIyNjQ5NDgtMzBlYmM4ZjAtNDMyMC00OTc4LWFmYWUtNjg3MGJiMmE5YzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDExMTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4M2E0ZTMyZDZmZGI2MTk1OTJmM2NmMTc1OGQ1NjBlNDNlMzQxNDczNGZmZDQyNjE4MTI3ZjUyMTQyZWY4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j6DR1TAipqCY5_6TSnt-sgXbFnd8RJQUcRvt9W8xqaM)
> 
> Might be that something in your setup overwrites `overflow: visible`.


Hi there, I just implemented your suggested styles in my css and no, it does not appear to resolve the issue. 

Below I've attached my css file. 
``` css
/*
Nodes
*/

.startNode{
    font-weight: bold;
    padding:10px;
    text-align: center;
    min-width: 75px;
    background: white;
    border: 1px solid lightgray;
    box-shadow: limegreen 0px 2px 4px, limegreen 0px 2px 4px;
    border-radius: 10px;
}


.startNode:hover{
    box-shadow: #32c2ff 0px 2px 4px, #32c2ff 0px 2px 4px;
}

.startNode::after {
    content:"" ;
    position: absolute;
    top: 15px;
    left: -15px;
    width: 0;
    height: 0;

    border-top: 5px solid transparent;
    border-bottom: 5px solid transparent;
    border-left: 10px solid limegreen;
}

.normalNode{
    padding: 10px;
    text-align: center;
    min-width: 75px;
    background: white;
    border: 1px solid lightgray;
    border-radius: 10px;
}

.normalNode:hover{
    box-shadow: #32c2ff 0px 2px 4px, #32c2ff 0px 2px 4px;
}

.endNode{
    padding:10px;
    text-align: center;
    min-width: 75px;
    background: white;
    border: 1px solid lightgray;
    box-shadow: red 0px 2px 4px, red 0px 2px 4px;;
    border-radius: 10px;
}

.endNode:hover{
    box-shadow: #32c2ff 0px 2px 4px, #32c2ff 0px 2px 4px;
}

.errorNode{
    padding:10px;
    text-align: center;
    min-width: 75px;
    background: red;
    border: 1px solid black;
    border-radius: 10px;
}

.errorNode:hover{
    box-shadow: #32c2ff 0px 2px 4px, #32c2ff 0px 2px 4px;
}


.selected{
    box-shadow: #32c2ff 0px 2px 4px, #32c2ff 0px 2px 4px;
}

/* 
Edges
*/
.react-flow__edge-path{
    stroke: #68c5ed;
}

.react-flow .react-flow__edges svg { 
    position:absolute;
    pointer-events: none;
    overflow: visible; 
} 


```
