### ISSUE TITLE
svelteflow: `selection` and `nodesselection-rect` are not separated

### ISSUE THREAD

**Issue by dror-weiss** [xyflow/xyflow#5338]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: @xyflow/svelte v1.0.2
- Browser and version: Arc v1.97.1
- OS and version: Mac Seqoia v15.5

### Describe the Bug

The selection rectangle should be applied with the class `svelte-flow__nodesselection-rect" whereas the selection itself with `svelte-flow__selection`. 

I want to implement styles for the rectangle with background and the node selection without background. Right now it's not working.

### Steps to reproduce the bug or issue

Override the styles with the following:
```css
.svelte-flow__nodesselection-rect {
  background-color: blue;
  border: 2px solid rgb(68, 68, 184);
}

.svelte-flow__selection {
  background-color: red;
}
```

The effect that is applied to the selection rectangle is only red, not blue.

### Expected behavior

As a use I expect the separation of classes to be applied on separate elements, but the current behavior is that the `.svelte-flow__nodesselection-rect` class has no effect.

**Comment by moklick** [comment]
Try this:

```css
.svelte-flow__selection {
  background-color: rgba(255, 0, 0, 0.5);
}

.svelte-flow__selection-wrapper .svelte-flow__selection {
  background-color: rgba(0, 0, 255, 0.5);
  border: 2px solid rgb(68, 68, 184);
}
```

We distinguish between a user selection (that's what is happening while you drag) and a nodes selection (that's the state when nodes got selected and the selection box stays). The nodes selection wraps the normal selection with a `.svelte-flow__selection-wrapper` class. 

https://stackblitz.com/edit/h1mlzyvi?file=src%2Findex.css
