### ISSUE TITLE
arrow heads should fallback to `--xy-edge-stroke` instead of a hardcoded color

### ISSUE THREAD

**Issue by m4rch3n1ng** [xyflow/xyflow#5366]
### Please describe the feature that you want to propose

when doing custom styles by overriding the `--xy-*` css variables it is currently impossible to change the color of the arrow heads, while it is possible to change the color of the edges. i would like it to default to the `var(--xy-edge-stroke, var(--xy-edge-stroke-default))` color like it does for the actual edges.

this is especially surprising, as the arrow heads *do* respect the `--xy-edge-stroke-width` variables.

i think this is because the fallback color is hardcoded to `#b1b1b7` (the same as `--xy-edge-stroke-default`) (i believe this happens [here](https://github.com/xyflow/xyflow/blob/67c576dc2952e359d914a3d47eb473502a300c3b/packages/svelte/src/lib/store/initial-store.svelte.ts#L368)).

in the app i'm making we currently have this style as a workaround:

```css
.svelte-flow {
	--xy-edge-stroke-width: 3;
	--xy-edge-stroke: var(--color-neutral-500);
}

/* this is the workaround */
.svelte-flow__arrowhead polyline {
	stroke: var(--xy-edge-stroke);
	fill: var(--xy-edge-stroke);
}
```

without the workaround style the arrows look like this:

![Image](https://github.com/user-attachments/assets/68cc133a-372e-400f-9ae3-ae65a56c53f8)

(where only the line is the correct color)
